# Generated by Django 4.1 on 2022-08-28 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_owner_alter_chatroom_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='messages',
            field=models.ManyToManyField(null=True, related_name='chat_messages', to='chat.message'),
        ),
    ]
