# Generated by Django 4.1 on 2022-08-28 23:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatroom_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='topic',
            field=models.TextField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
