# Generated by Django 4.1 on 2022-08-29 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatroom_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='messages',
            field=models.ManyToManyField(related_name='chat_messages', to='chat.message'),
        ),
    ]
