# Generated by Django 4.1 on 2022-08-30 12:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_chatroom_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='time_created',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
