# Generated by Django 4.1 on 2022-09-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='isPrivate',
            field=models.BooleanField(default=True),
        ),
    ]
