# Generated by Django 4.1 on 2022-09-01 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chatroom_isprivate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='last_updated',
        ),
    ]
