# Generated by Django 4.1 on 2022-09-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_chatroom_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='chat_messages', to='chat.message'),
        ),
    ]
