# Generated by Django 4.1 on 2022-09-07 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_chatroom_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='dp',
            field=models.ImageField(blank=True, default='images/profile/groupicon.svg', upload_to='images/profile/'),
        ),
    ]
