# Generated by Django 4.1 on 2022-09-07 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_chatroom_dp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='isPrivate',
        ),
    ]
