# Generated by Django 4.1 on 2022-09-08 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_alter_chatroom_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='topic',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
