# Generated by Django 4.1 on 2022-09-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/profile/defaultprofile.png', upload_to='images/profile/'),
        ),
    ]
