# Generated by Django 4.1 on 2022-09-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/profile/defaultprofile.svg', upload_to='images/profile/'),
        ),
    ]
