# Generated by Django 4.1 on 2022-09-10 00:02

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.ImageField(upload_to=accounts.models.user_directory_path)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='images/profile/defaultprofile.svg', upload_to=accounts.models.user_directory_path),
        ),
    ]
